[package]
name = "kalavor"
version = "0.1.0"
edition = "2021"
authors = ["K--A"]

description = "K--A flavored contents."

documentation = "https://docs.rs/kalavor"
repository = "https://github.com/eternal-io/kalavor"
license = "MIT OR Apache-2.0"
readme = false

keywords = ["KA", "flavored", "content"]
categories = ["value-formatting", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
radix_fmt = "1.0.0"
